// nobles
export const TILES = [
  {
    id: 1,
    cost: { white: 4, blue: 4 },
    points: 3,
  },
  {
    id: 2,
    cost: { blue: 4, green: 4 },
    points: 3,
  },
  {
    id: 3,
    cost: { green: 4, red: 4 },
    points: 3,
  },
  {
    id: 4,
    cost: { red: 4, black: 4 },
    points: 3,
  },
  {
    id: 5,
    cost: { black: 4, white: 4 },
    points: 3,
  },
  {
    id: 6,
    cost: { white: 3, blue: 3, black: 3 },
    points: 3,
  },
  {
    id: 7,
    cost: { blue: 3, green: 3, white: 3 },
    points: 3,
  },
  {
    id: 8,
    cost: { green: 3, red: 3, blue: 3 },
    points: 3,
  },
  {
    id: 9,
    cost: { red: 3, black: 3, green: 3 },
    points: 3,
  },
  {
    id: 10,
    cost: { black: 3, white: 3, red: 3 },
    points: 3,
  },
];

export const TOKENS = [
  // two players
  {
    red: 4,
    green: 4,
    blue: 4,
    white: 4,
    black: 4,
    gold: 5,
  },
  // three players
  {
    red: 5,
    green: 5,
    blue: 5,
    white: 5,
    black: 5,
    gold: 5,
  },
  // four players
  {
    red: 7,
    green: 7,
    blue: 7,
    white: 7,
    black: 7,
    gold: 5,
  },
];

export const WIN_CONDITION = 15;

export const LEVEL_1 = [
  {
    id: 1,
    cost: { red: 2, green: 0, blue: 2, white: 0, black: 0 },
    points: 0,
    token: 'green',
    level: 1 as const,
    img: '/public/grass/bulbasaur',
  },
  {
    id: 2,
    cost: { red: 2, green: 0, blue: 0, white: 2, black: 0 },
    points: 0,
    token: 'red',
    level: 1 as const,
    img: '/public/fire/charmander',
  },
  {
    id: 3,
    cost: { red: 0, green: 0, blue: 0, white: 1, black: 2 },
    points: 0,
    token: 'blue',
    level: 1 as const,
    img: '/public/water/squirtle',
  },
  {
    id: 4,
    cost: { red: 1, green: 2, blue: 1, white: 0, black: 1 },
    points: 0,
    token: 'white',
    level: 1 as const,
    img: '/public/normal/pidgey',
  },
  {
    id: 5,
    cost: { red: 3, green: 1, blue: 0, white: 0, black: 1 },
    points: 0,
    token: 'black',
    level: 1 as const,
    img: '/public/ground/nidoran',
  },

  {
    id: 6,
    cost: { red: 0, green: 0, blue: 0, white: 3, black: 0 },
    points: 0,
    token: 'red',
    level: 1 as const,
    img: '/public/fire/charmander',
  },
  {
    id: 7,
    cost: { red: 0, green: 0, blue: 0, white: 0, black: 3 },
    points: 0,
    token: 'blue',
    level: 1 as const,
    img: '/public/water/squirtle',
  },
  {
    id: 8,
    cost: { red: 0, green: 2, blue: 2, white: 0, black: 1 },
    points: 0,
    token: 'white',
    level: 1 as const,
    img: '/public/normal/pidgey',
  },
  {
    id: 9,
    cost: { red: 1, green: 1, blue: 2, white: 1, black: 0 },
    points: 0,
    token: 'black',
    level: 1 as const,
    img: '/public/ground/nidoran',
  },
  {
    id: 10,
    cost: { red: 1, green: 0, blue: 1, white: 1, black: 1 },
    points: 0,
    token: 'green',
    level: 1 as const,
    img: '/public/grass/bulbasaur',
  },

  {
    id: 11,
    cost: { red: 0, green: 1, blue: 2, white: 0, black: 0 },
    points: 0,
    token: 'red',
    level: 1 as const,
    img: '/public/fire/charmander',
  },
  {
    id: 12,
    cost: { red: 3, green: 0, blue: 0, white: 0, black: 0 },
    points: 0,
    token: 'green',
    level: 1 as const,
    img: '/public/grass/bulbasaur',
  },
  {
    id: 13,
    cost: { red: 2, green: 1, blue: 0, white: 1, black: 1 },
    points: 0,
    token: 'blue',
    level: 1 as const,
    img: '/public/water/squirtle',
  },
  {
    id: 14,
    cost: { red: 0, green: 0, blue: 1, white: 3, black: 1 },
    points: 0,
    token: 'white',
    level: 1 as const,
    img: '/public/normal/pidgey',
  },
  {
    id: 15,
    cost: { red: 1, green: 0, blue: 2, white: 2, black: 0 },
    points: 0,
    token: 'black',
    level: 1 as const,
    img: '/public/ground/nidoran',
  },

  {
    id: 16,
    cost: { red: 1, green: 0, blue: 1, white: 1, black: 2 },
    points: 0,
    token: 'green',
    level: 1 as const,
    img: '/public/grass/bulbasaur',
  },
  {
    id: 17,
    cost: { red: 0, green: 1, blue: 0, white: 2, black: 2 },
    points: 0,
    token: 'red',
    level: 1 as const,
    img: '/public/fire/charmander',
  },
  {
    id: 18,
    cost: { red: 0, green: 2, blue: 0, white: 0, black: 2 },
    points: 0,
    token: 'blue',
    level: 1 as const,
    img: '/public/water/squirtle',
  },
  {
    id: 19,
    cost: { red: 0, green: 0, blue: 2, white: 0, black: 2 },
    points: 0,
    token: 'white',
    level: 1 as const,
    img: '/public/normal/pidgey',
  },
  {
    id: 20,
    cost: { red: 1, green: 2, blue: 0, white: 0, black: 0 },
    points: 0,
    token: 'black',
    level: 1 as const,
    img: '/public/ground/nidoran',
  },

  {
    id: 21,
    cost: { red: 0, green: 1, blue: 1, white: 1, black: 1 },
    points: 0,
    token: 'red',
    level: 1 as const,
    img: '/public/fire/charmander',
  },
  {
    id: 22,
    cost: { red: 1, green: 3, blue: 1, white: 0, black: 0 },
    points: 0,
    token: 'blue',
    level: 1 as const,
    img: '/public/water/squirtle',
  },
  {
    id: 23,
    cost: { red: 0, green: 0, blue: 3, white: 0, black: 0 },
    points: 0,
    token: 'white',
    level: 1 as const,
    img: '/public/normal/pidgey',
  },
  {
    id: 24,
    cost: { red: 0, green: 0, blue: 1, white: 2, black: 0 },
    points: 0,
    token: 'green',
    level: 1 as const,
    img: '/public/grass/bulbasaur',
  },
  {
    id: 25,
    cost: { red: 0, green: 3, blue: 0, white: 0, black: 0 },
    points: 0,
    token: 'black',
    level: 1 as const,
    img: '/public/ground/nidoran',
  },

  {
    id: 26,
    cost: { red: 2, green: 2, blue: 0, white: 1, black: 0 },
    points: 0,
    token: 'blue',
    level: 1 as const,
    img: '/public/water/squirtle',
  },
  {
    id: 27,
    cost: { red: 2, green: 0, blue: 1, white: 0, black: 2 },
    points: 0,
    token: 'green',
    level: 1 as const,
    img: '/public/grass/bulbasaur',
  },
  {
    id: 28,
    cost: { red: 0, green: 1, blue: 1, white: 2, black: 1 },
    points: 0,
    token: 'red',
    level: 1 as const,
    img: '/public/fire/charmander',
  },
  {
    id: 29,
    cost: { red: 2, green: 0, blue: 0, white: 0, black: 1 },
    points: 0,
    token: 'white',
    level: 1 as const,
    img: '/public/normal/pidgey',
  },
  {
    id: 30,
    cost: { red: 0, green: 2, blue: 0, white: 2, black: 0 },
    points: 0,
    token: 'black',
    level: 1 as const,
    img: '/public/ground/nidoran',
  },

  {
    id: 31,
    cost: { red: 1, green: 1, blue: 0, white: 1, black: 1 },
    points: 0,
    token: 'blue',
    level: 1 as const,
    img: '/public/water/squirtle',
  },
  {
    id: 32,
    cost: { red: 1, green: 0, blue: 0, white: 1, black: 3 },
    points: 0,
    token: 'red',
    level: 1 as const,
    img: '/public/fire/charmander',
  },
  {
    id: 33,
    cost: { red: 0, green: 1, blue: 3, white: 1, black: 0 },
    points: 0,
    token: 'green',
    level: 1 as const,
    img: '/public/grass/bulbasaur',
  },
  {
    id: 34,
    cost: { red: 1, green: 1, blue: 1, white: 0, black: 1 },
    points: 0,
    token: 'white',
    level: 1 as const,
    img: '/public/normal/pidgey',
  },
  {
    id: 35,
    cost: { red: 1, green: 1, blue: 1, white: 1, black: 0 },
    points: 0,
    token: 'black',
    level: 1 as const,
    img: '/public/ground/nidoran',
  },

  {
    id: 36,
    cost: { red: 0, green: 0, blue: 0, white: 4, black: 0 },
    points: 1,
    token: 'red',
    level: 1 as const,
    img: '/public/fire/charmander',
  },
  {
    id: 37,
    cost: { red: 0, green: 0, blue: 0, white: 0, black: 4 },
    points: 1,
    token: 'green',
    level: 1 as const,
    img: '/public/grass/bulbasaur',
  },
  {
    id: 38,
    cost: { red: 4, green: 1, blue: 0, white: 0, black: 0 },
    points: 1,
    token: 'blue',
    level: 1 as const,
    img: '/public/water/squirtle',
  },
  {
    id: 39,
    cost: { red: 0, green: 4, blue: 0, white: 0, black: 0 },
    points: 1,
    token: 'white',
    level: 1 as const,
    img: '/public/normal/pidgey',
  },
  {
    id: 40,
    cost: { red: 0, green: 0, blue: 4, white: 0, black: 0 },
    points: 1,
    token: 'black',
    level: 1 as const,
    img: '/public/ground/nidoran',
  },
];

export const LEVEL_2 = [
  {
    id: 41,
    cost: { red: 2, green: 0, blue: 3, white: 0, black: 3 },
    points: 1,
    token: 'red',
    level: 2 as const,
    img: '/public/fire/charmeleon',
  },
  {
    id: 42,
    cost: { red: 3, green: 2, blue: 0, white: 3, black: 0 },
    points: 1,
    token: 'green',
    level: 2 as const,
    img: '/public/grass/ivysaur',
  },
  {
    id: 43,
    cost: { red: 3, green: 2, blue: 2, white: 0, black: 0 },
    points: 1,
    token: 'blue',
    level: 2 as const,
    img: '/public/water/wartortle',
  },
  {
    id: 44,
    cost: { red: 2, green: 3, blue: 0, white: 0, black: 2 },
    points: 1,
    token: 'white',
    level: 2 as const,
    img: '/public/normal/pidgeotto',
  },
  {
    id: 45,
    cost: { red: 0, green: 3, blue: 0, white: 3, black: 2 },
    points: 1,
    token: 'black',
    level: 2 as const,
    img: '/public/ground/nidorina',
  },

  {
    id: 46,
    cost: { red: 2, green: 0, blue: 0, white: 2, black: 3 },
    points: 1,
    token: 'red',
    level: 2 as const,
    img: '/public/fire/charmeleon',
  },
  {
    id: 47,
    cost: { red: 0, green: 0, blue: 3, white: 2, black: 2 },
    points: 1,
    token: 'green',
    level: 2 as const,
    img: '/public/grass/ivysaur',
  },
  {
    id: 48,
    cost: { red: 0, green: 3, blue: 2, white: 0, black: 3 },
    points: 1,
    token: 'blue',
    level: 2 as const,
    img: '/public/water/wartortle',
  },
  {
    id: 49,
    cost: { red: 3, green: 0, blue: 3, white: 2, black: 0 },
    points: 1,
    token: 'white',
    level: 2 as const,
    img: '/public/normal/pidgeotto',
  },
  {
    id: 50,
    cost: { red: 0, green: 2, blue: 2, white: 3, black: 0 },
    points: 1,
    token: 'black',
    level: 2 as const,
    img: '/public/ground/nidorina',
  },

  {
    id: 51,
    cost: { red: 0, green: 0, blue: 5, white: 0, black: 0 },
    points: 2,
    token: 'blue',
    level: 2 as const,
    img: '/public/water/wartortle',
  },
  {
    id: 52,
    cost: { red: 0, green: 0, blue: 0, white: 0, black: 5 },
    points: 2,
    token: 'red',
    level: 2 as const,
    img: '/public/fire/charmeleon',
  },
  {
    id: 53,
    cost: { red: 0, green: 5, blue: 0, white: 0, black: 0 },
    points: 2,
    token: 'green',
    level: 2 as const,
    img: '/public/grass/ivysaur',
  },
  {
    id: 54,
    cost: { red: 5, green: 0, blue: 0, white: 0, black: 3 },
    points: 2,
    token: 'white',
    level: 2 as const,
    img: '/public/normal/pidgeotto',
  },
  {
    id: 55,
    cost: { red: 0, green: 0, blue: 0, white: 5, black: 0 },
    points: 2,
    token: 'black',
    level: 2 as const,
    img: '/public/ground/nidorina',
  },

  {
    id: 56,
    cost: { red: 0, green: 3, blue: 5, white: 0, black: 0 },
    points: 2,
    token: 'green',
    level: 2 as const,
    img: '/public/grass/ivysaur',
  },
  {
    id: 57,
    cost: { red: 0, green: 0, blue: 3, white: 5, black: 0 },
    points: 2,
    token: 'blue',
    level: 2 as const,
    img: '/public/water/wartortle',
  },
  {
    id: 58,
    cost: { red: 5, green: 0, blue: 0, white: 0, black: 0 },
    points: 2,
    token: 'white',
    level: 2 as const,
    img: '/public/normal/pidgeotto',
  },
  {
    id: 59,
    cost: { red: 3, green: 5, blue: 0, white: 0, black: 0 },
    points: 2,
    token: 'black',
    level: 2 as const,
    img: '/public/ground/nidorina',
  },
  {
    id: 60,
    cost: { red: 0, green: 0, blue: 0, white: 3, black: 5 },
    points: 2,
    token: 'red',
    level: 2 as const,
    img: '/public/fire/charmeleon',
  },

  {
    id: 61,
    cost: { red: 1, green: 0, blue: 0, white: 2, black: 4 },
    points: 2,
    token: 'blue',
    level: 2 as const,
    img: '/public/water/wartortle',
  },
  {
    id: 62,
    cost: { red: 2, green: 4, blue: 1, white: 0, black: 0 },
    points: 2,
    token: 'black',
    level: 2 as const,
    img: '/public/ground/nidorina',
  },
  {
    id: 63,
    cost: { red: 0, green: 0, blue: 2, white: 4, black: 1 },
    points: 2,
    token: 'green',
    level: 2 as const,
    img: '/public/grass/ivysaur',
  },
  {
    id: 64,
    cost: { red: 0, green: 2, blue: 4, white: 1, black: 0 },
    points: 2,
    token: 'red',
    level: 2 as const,
    img: '/public/fire/charmeleon',
  },
  {
    id: 65,
    cost: { red: 4, green: 1, blue: 0, white: 0, black: 2 },
    points: 2,
    token: 'white',
    level: 2 as const,
    img: '/public/normal/pidgeotto',
  },

  {
    id: 66,
    cost: { red: 0, green: 0, blue: 6, white: 0, black: 0 },
    points: 3,
    token: 'blue',
    level: 2 as const,
    img: '/public/water/wartortle',
  },
  {
    id: 67,
    cost: { red: 6, green: 0, blue: 0, white: 0, black: 0 },
    points: 3,
    token: 'red',
    level: 2 as const,
    img: '/public/fire/charmeleon',
  },
  {
    id: 68,
    cost: { red: 0, green: 6, blue: 0, white: 0, black: 0 },
    points: 3,
    token: 'green',
    level: 2 as const,
    img: '/public/grass/ivysaur',
  },
  {
    id: 69,
    cost: { red: 0, green: 0, blue: 0, white: 6, black: 0 },
    points: 3,
    token: 'white',
    level: 2 as const,
    img: '/public/normal/pidgeotto',
  },
  {
    id: 70,
    cost: { red: 0, green: 0, blue: 0, white: 0, black: 6 },
    points: 3,
    token: 'black',
    level: 2 as const,
    img: '/public/ground/nidorina',
  },
];

export const LEVEL_3 = [
  {
    id: 71,
    cost: { red: 0, green: 3, blue: 5, white: 3, black: 3 },
    points: 3,
    token: 'red',
    level: 3 as const,
    img: '/public/fire/charizard',
  },
  {
    id: 72,
    cost: { red: 3, green: 0, blue: 3, white: 5, black: 3 },
    points: 3,
    token: 'green',
    level: 3 as const,
    img: '/public/grass/venusaur',
  },
  {
    id: 73,
    cost: { red: 3, green: 3, blue: 0, white: 3, black: 5 },
    points: 3,
    token: 'blue',
    level: 3 as const,
    img: '/public/water/blastoise',
  },
  {
    id: 74,
    cost: { red: 5, green: 3, blue: 3, white: 0, black: 3 },
    points: 3,
    token: 'white',
    level: 3 as const,
    img: '/public/normal/pigeot',
  },
  {
    id: 75,
    cost: { red: 3, green: 5, blue: 3, white: 3, black: 0 },
    points: 3,
    token: 'black',
    level: 3 as const,
    img: '/public/ground/nidoking',
  },

  {
    id: 76,
    cost: { red: 3, green: 0, blue: 0, white: 3, black: 6 },
    points: 3,
    token: 'white',
    level: 3 as const,
    img: '/public/normal/pigeot',
  },
  {
    id: 77,
    cost: { red: 0, green: 3, blue: 6, white: 3, black: 0 },
    points: 3,
    token: 'green',
    level: 3 as const,
    img: '/public/grass/venusaur',
  },
  {
    id: 78,
    cost: { red: 3, green: 6, blue: 3, white: 0, black: 0 },
    points: 3,
    token: 'red',
    level: 3 as const,
    img: '/public/fire/charizard',
  },
  {
    id: 79,
    cost: { red: 0, green: 0, blue: 3, white: 6, black: 3 },
    points: 3,
    token: 'blue',
    level: 3 as const,
    img: '/public/water/blastoise',
  },
  {
    id: 80,
    cost: { red: 6, green: 3, blue: 0, white: 0, black: 3 },
    points: 3,
    token: 'black',
    level: 3 as const,
    img: '/public/ground/nidoking',
  },

  {
    id: 81,
    cost: { red: 0, green: 0, blue: 7, white: 0, black: 0 },
    points: 4,
    token: 'green',
    level: 3 as const,
    img: '/public/grass/venusaur',
  },
  {
    id: 82,
    cost: { red: 0, green: 0, blue: 0, white: 7, black: 0 },
    points: 4,
    token: 'blue',
    level: 3 as const,
    img: '/public/water/blastoise',
  },
  {
    id: 83,
    cost: { red: 0, green: 0, blue: 0, white: 0, black: 7 },
    points: 4,
    token: 'white',
    level: 3 as const,
    img: '/public/normal/pigeot',
  },
  {
    id: 84,
    cost: { red: 7, green: 0, blue: 0, white: 0, black: 0 },
    points: 4,
    token: 'black',
    level: 3 as const,
    img: '/public/ground/nidoking',
  },
  {
    id: 85,
    cost: { red: 0, green: 7, blue: 0, white: 0, black: 0 },
    points: 4,
    token: 'red',
    level: 3 as const,
    img: '/public/fire/charizard',
  },

  {
    id: 86,
    cost: { red: 3, green: 7, blue: 0, white: 0, black: 0 },
    points: 5,
    token: 'red',
    level: 3 as const,
    img: '/public/fire/charizard',
  },
  {
    id: 87,
    cost: { red: 0, green: 3, blue: 7, white: 0, black: 0 },
    points: 5,
    token: 'green',
    level: 3 as const,
    img: '/public/grass/venusaur',
  },
  {
    id: 88,
    cost: { red: 0, green: 0, blue: 3, white: 7, black: 0 },
    points: 5,
    token: 'blue',
    level: 3 as const,
    img: '/public/water/blastoise',
  },
  {
    id: 89,
    cost: { red: 0, green: 0, blue: 0, white: 3, black: 7 },
    points: 5,
    token: 'white',
    level: 3 as const,
    img: '/public/normal/pigeot',
  },
  {
    id: 90,
    cost: { red: 7, green: 0, blue: 0, white: 0, black: 3 },
    points: 5,
    token: 'black',
    level: 3 as const,
    img: '/public/ground/nidoking',
  },
];
